
sudo: false 

language: java
# Set display to execute UI tests on

jdk: oraclejdk8

# Install recent maven version since we need polyglot support
# which was introduced in maven 3.3
before_install:
 # Only download maven if it wasn't cached
 - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn clean verify -q

notifications:
  email: false
